apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
  namespace: default
spec:
  completions: 1000
  parallelism: 4
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: c
        image: abrahamleal/job
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 10Gi
          requests:
            cpu: 200m
            memory: 512Mi
            ephemeral-storage: 5Gi
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: work
      restartPolicy: OnFailure