apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/name: weightsandbiases
    wandb.ai/console-default: "true"
  name: wandb
  namespace: default
spec:
  values:
    global:
      host: https://abe-sm.wandb.ml
      cloudProvider: "aws"
      license: eyJhbGciOiJSUzI1NiIsImtpZCI6InUzaHgyQjQyQWhEUXM1M0xQY09yNnZhaTdoSlduYnF1bTRZTlZWd1VwSWM9In0.eyJjb25jdXJyZW50QWdlbnRzIjoxMCwiZGVwbG95bWVudElkIjoiZDQxNmFkN2YtNTQ5Yi00NTMzLTkxYWMtNDc2NDg3Yzg1MThiIiwibWF4VXNlcnMiOjUwLCJtYXhWaWV3T25seVVzZXJzIjoyMCwibWF4U3RvcmFnZUdiIjoxMDAwMDAwMCwibWF4VGVhbXMiOjEwMCwibWF4UmVnaXN0ZXJlZE1vZGVscyI6NSwiZXhwaXJlc0F0IjoiMjAzMC0xMi0xNlQwNzo1OTo1OS45OTlaIiwiZmxhZ3MiOlsiU0NBTEFCTEUiLCJteXNxbCIsInMzIiwicmVkaXMiLCJOT1RJRklDQVRJT05TIiwic2xhY2siLCJub3RpZmljYXRpb25zIiwiTUFOQUdFTUVOVCIsIm9yZ19kYXNoIiwiYXV0aDAiLCJjb2xsZWN0X2F1ZGl0X2xvZ3MiLCJyYmFjIiwiQllPQiIsImJ5b2IiLCJMQVVOQ0hfQ0xVU1RFUlMiLCJsYXVuY2hfY2x1c3RlcnMiXSwidHJpYWwiOmZhbHNlLCJhY2Nlc3NLZXkiOiJiMjM5MmViZC0yZTljLTRkZGUtYTk5Ni1lMGFiYmYyYWU1YTEiLCJzZWF0cyI6NTAsInZpZXdPbmx5U2VhdHMiOjIwLCJ0ZWFtcyI6MTAwLCJyZWdpc3RlcmVkTW9kZWxzIjo1LCJzdG9yYWdlR2lncyI6MTAwMDAwMDAsImV4cCI6MTkyMzYzODM5OX0.CEglDoVnWJyIlCG6jEaTLyD4-Q7AghIouOKC3QueY9YXInT2IW5PtRJ4DEVB61ViaR50I9LxkxNcAek01qVIhK56xkgJ-p7mdIdOtXW4IigGrclERYiPsg6jVX1PTF1MxwJ3h1kPgqtMzpZkJpiJ_-XUGLBxaCjXorjuTieHsMFgjLGi-7Bq8tfgnlXtSteeEC_gLs3wGGhQSfbNtBedWi7qQJiNP7Ht_wfMpwfPBweFBKEJr8ffFFma5nniBHPiE-RUIebF9tB4XK5CS-lPGQ011o088t_0peCL13L27y9QvMIjooW7qslmgOLA51tK_86HjqB1Xx-KtSbE6XdzFA


      # This is an example using AWS S3 bucket with the IAM permissions already set for the EKS nodes
      defaultBucket:
        accessKey: 
        secretKey: 
        name: abe-fake-bucket-info
        provider: s3
        region: us-east-1

      mysql:
        database: wandb
        host: abe-test-wandb-mysql-instance-1.cbz4oaw8p6rp.us-east-1.rds.amazonaws.com
        password: XXX
        port: 3306
        user: wandb

      redis:
        host: "abe-redis-cache-w9awdi.serverless.use1.cache.amazonaws.com"
        port: 6379
        password: "somepassforredis"

      extraEnv:
        BUCKET_QUEUE: internal://

    mysql:
      install: false

    redis:
      install: false
    
    kafka:
      install: false
    
    flat-run-fields-updater:
      install: false
    
    otel:
      install: false

    prometheus:
      install: false

    yace:
      install: false

    app:
      image:
        repository: wandb/local
        tag: latest
      extraEnv:
        GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS: true
        SERVER_FLAG_NAMED_WORKSPACES_AVAILABLE: true
        ENABLE_REGISTRY_UI: true

    parquet:
      install: true
      image:
        repository: wandb/local
        tag: latest

    weave:
      install: true
      image:
        repository: wandb/local
        tag: latest

    weave-trace:
      install: false
      image:
        repository: wandb/weave-trace
        tag: latest
      datadog:
        enabled: false

    console:
      install: true
      image:
        repository: wandb/console
        tag: latest

    # This is an example of how to configure the ingress for the app using NGINX.
    # For AWS plese refer to this link: https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/examples/aws/ingress.yaml
    ingress:
      install: true
      create: true
      defaultBackend: "app"
      issuer:
        create: false
        provider: ""
        server: https://acme-v02.api.letsencrypt.org/directory
        email: support@wandb.com
      class: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 64m
      hosts:
        - host: abe-sm.wandb.ml
          paths:
            - path: /